language: java
sudo: true
jdk:
  - oraclejdk8
env:  
  global:  
    - DISPLAY=:99.0  
cache:
  directories:
   - $HOME/.m2

notifications:
  email:
    recipients:
      - vitruv-build@ira.uni-karlsruhe.de

# Enable UI
before_install:
    - sh -e /etc/init.d/xvfb start - sleep 10
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/installMaven.sh
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh applications/cbs releng/tools.vitruv.applications.cbs.updatesite repository vitruv-tools updatesite